<a href="https://colab.research.google.com/github/dikshikaaa/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy =  Numerical Operations

In [ ]:
import numpy as np

List vs. Numpy

Time efficiency and more operations possible

In [ ]:
from time import process_time

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time )

0.0011931519999999196


In [ ]:
np_array = np.array ([i for i in range(100)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time )

6.827499999983999e-05


Dimentional Array

In [ ]:
#1 dimentional
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
print(np_array.shape)

[1 2 3 4 5]
(5,)


In [ ]:
#1 dimentional
np_array = np.array([(1, 2, 3, 4, 5)])
print(np_array)
print(np_array.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
#2dimentional
np_array2 = np.array([(1, 2, 3, 4, 5), (8, 9, 0, 7, 6)])
print(np_array2)
print(np_array2.shape)
#1st value represents rows and 2nd the no of columns

[[1 2 3 4 5]
 [8 9 0 7 6]]
(2, 5)


Changing data type in array

In [ ]:
#making all data type float since default is integers
np_array3 = np.array([(1, 2, 3, 4, 5), (8, 9, 0, 7, 6)], dtype = float)
print(np_array3)

[[1. 2. 3. 4. 5.]
 [8. 9. 0. 7. 6.]]


In [ ]:
#making all data type float by making some of the elements float
np_array3 = np.array([(1, 2.2, 3, 4.9, 5), (8, 9.5, 0, 7, 6)])
print(np_array3)

[[1.  2.2 3.  4.9 5. ]
 [8.  9.5 0.  7.  6. ]]


In [ ]:
#making all data type float by making one of the elements float
np_array3 = np.array([(1, 2., 3, 4, 5), (8, 9, 0, 7, 6)])
print(np_array3)

[[1. 2. 3. 4. 5.]
 [8. 9. 0. 7. 6.]]


Initial Placeholder in numpy array

In [ ]:
#creating an array of zeroes
x = np.zeros((4, 5))
print(x)
y = np.ones((3, 3))
print(y)
#numpy has no attributes of twos or threes or tens etc. etc.

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#for getting a particular number
z = np.full((3, 4), 15)
print(z)

[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [ ]:
#creating identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#creat a numpy with random values
b = np.random.random((3,5))
print(b)
#all values will be between 0 to 1(default)

[[0.31787877 0.86339998 0.86425449 0.55976754 0.23684218]
 [0.80671999 0.1914891  0.91127821 0.00715152 0.55080421]
 [0.02553693 0.69450237 0.12569013 0.876268   0.48481697]]


In [ ]:
#random values which are intergers within a specific range
c = np.random.randint(10, 100, (3, 5))
print(c)

[[48 13 77 16 24]
 [26 16 20 23 74]
 [68 67 65 73 60]]


In [ ]:
#array of evenly spaced values
d = np.linspace(10, 30, 5)
print(d)
#where 5 is the number of values to be printed

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaced values
e = np.arange(10, 30, 5)
print(e)
#where 5 is the step value
f = np.arange(10, 30, 6)
print(f)

[10 15 20 25]
[10 16 22 28]


Converting list to numpy array and vice-versa

In [ ]:
#converting list to numpy array
list2 = [2, 4, 6, 8, 5, 3, 9]

np_arr = np.asarray(list2)
print (np_arr)
type(np_arr)

[2 4 6 8 5 3 9]


numpy.ndarray

In [ ]:
#converting array to list
arr = np.array([4, 5, 6, 7, 8, 3])
l = arr.tolist()
print(l)
type(l)

[4, 5, 6, 7, 8, 3]


list

Analyzing a numpy array

In [ ]:
m = np.random.randint(10, 90, (5, 5, 2))
print(m)

[[[15 66]
  [47 45]
  [55 33]
  [56 86]
  [89 89]]

 [[12 60]
  [24 39]
  [52 64]
  [15 57]
  [21 44]]

 [[10 67]
  [69 66]
  [39 13]
  [57 89]
  [15 28]]

 [[27 46]
  [30 42]
  [67 16]
  [17 32]
  [27 37]]

 [[85 25]
  [65 20]
  [51 88]
  [33 66]
  [37 10]]]


In [ ]:
#dimentions of the array
print(m.shape)
#no of dimentions of the array
print(m.ndim)
#no of elements in the array
print(m.size)
#data type of the array
print(m.dtype)

(5, 5, 2)
3
50
int64


Mathematical operation on nparray

In [ ]:
list1 = [1, 3, 5, 7, 8, 2]
list2 = [4, 5, 6, 7, 8, 3]
print(list1 + list2)
#not add the elements but concatenates both lists

[1, 3, 5, 7, 8, 2, 4, 5, 6, 7, 8, 3]


In [ ]:
p = np.array([1, 3, 5, 7, 8, 2])
q = np.array([4, 5, 6, 7, 8, 3])
print(p + q)
#add the elements but not concatenates both lists
print(p - q)
print(p * q)
print(p / q)

[ 5  8 11 14 16  5]
[-3 -2 -1  0  0 -1]
[ 4 15 30 49 64  6]
[0.25       0.6        0.83333333 1.         1.         0.66666667]


In [ ]:
#p = np.array([1, 3, 5, 7, 8, 2])
#q = np.array([4, 5, 6, 7])
#print(p + q)
#print(p - q)
#Eroor because different sizes of array

In [ ]:
m = np.random.randint(10, 90, (3, 3))
n = np.random.randint(90, 190, (3, 3))
print(m)
print(n)

[[80 15 14]
 [32 36 30]
 [85 66 87]]
[[171 189 182]
 [ 97 130 159]
 [113 125 132]]


In [ ]:
print(np.add(m, n))
print(np.subtract(m, n))
print(np.multiply(m, n))
print(np.divide(m, n))

[[251 204 196]
 [129 166 189]
 [198 191 219]]
[[ -91 -174 -168]
 [ -65  -94 -129]
 [ -28  -59  -45]]
[[13680  2835  2548]
 [ 3104  4680  4770]
 [ 9605  8250 11484]]
[[0.46783626 0.07936508 0.07692308]
 [0.32989691 0.27692308 0.18867925]
 [0.75221239 0.528      0.65909091]]


ARRAY MANIPULATION

In [ ]:
array  = np.random.randint(10, 90, (3,4))
print(array)
print(array.shape)

[[89 26 32 62]
 [37 31 47 67]
 [32 72 12 51]]
(3, 4)


Transnpose of array

In [ ]:
t = np.transpose(array)
print(t)
print(t.shape)

[[89 37 32]
 [26 31 72]
 [32 47 12]
 [62 67 51]]
(4, 3)


In [ ]:
array2 = np.random.randint(10, 90, (3,2))
print(array2)
print(array2.shape)

[[26 37]
 [35 54]
 [62 71]]
(3, 2)


In [ ]:
t2 = array.T
print(t2)
print(t2.shape)

[[89 37 32]
 [26 31 72]
 [32 47 12]
 [62 67 51]]
(4, 3)


### Reshaping array
Same as transpose ig

In [ ]:
a = np.random.randint(10, 90, (5, 10))
print(a)
print(a.shape)

[[71 20 57 41 74 87 75 29 47 13]
 [89 82 57 79 21 84 70 32 25 89]
 [27 59 56 55 37 26 42 70 57 22]
 [25 17 41 49 59 70 31 34 45 79]
 [31 38 88 68 60 67 88 17 10 74]]
(5, 10)


In [ ]:
b = a.reshape(25, 2)
print(b)
print(b.shape)

[[71 20]
 [57 41]
 [74 87]
 [75 29]
 [47 13]
 [89 82]
 [57 79]
 [21 84]
 [70 32]
 [25 89]
 [27 59]
 [56 55]
 [37 26]
 [42 70]
 [57 22]
 [25 17]
 [41 49]
 [59 70]
 [31 34]
 [45 79]
 [31 38]
 [88 68]
 [60 67]
 [88 17]
 [10 74]]
(25, 2)
